server:
  port: 5003

spring:
  application:
    name: job-portal-job-service






  datasource:
    url: jdbc:postgresql://localhost:5434/melex_job_portal_job
    username: postgres
    password: Itzsplitz
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
